[kobis_daily]
title = "KOBIS ─ 일별 박스오피스"
url = "https://www.kobis.or.kr/kobis/mobile/main/findDailyBoxOfficeList.do"
entrySelector = "ul.list_mvie li"
titleSelector = "strong.tit.ellip"
linkSelector = "a"
contentSelector = "div.desc"
imageSelector = "span.thumb.boxofimg img"
waitUntil = "networkidle"

[kobis_weekly]
title = "KOBIS ─ 주간 박스오피스"
url = "https://www.kobis.or.kr/kobis/mobile/main/findWeeklyBoxOfficeList.do?sWeekGb=0"
entrySelector = "ul.list_mvie li"
titleSelector = "strong.tit.ellip"
linkSelector = "a"
contentSelector = "div.desc"
imageSelector = "span.thumb.boxofimg img"
waitUntil = "networkidle"

[kobis_weekend]
title = "KOBIS ─ 주말 박스오피스"
url = "https://www.kobis.or.kr/kobis/mobile/main/findWeeklyBoxOfficeList.do?sWeekGb=1"
entrySelector = "ul.list_mvie li"
titleSelector = "strong.tit.ellip"
linkSelector = "a"
contentSelector = "div.desc"
imageSelector = "span.thumb.boxofimg img"
waitUntil = "networkidle"
